version: '3.8'
services:
  quasar:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8080:80'
  capacitor:
    build:
      context: .
      dockerfile: ./src-capacitor/Dockerfile
    ports:
      - '8000:80'
